services:
  autofc2:
    container_name: autofc2
    image: ghcr.io/jim60105/fc2-live-dl:latest
    user: "1001:0"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1001
      cache_from:
        - ghcr.io/jim60105/fc2-live-dl:cache
      cache_to:
        - type=inline
    entrypoint: [ "dumb-init", "--", "autofc2" ]
    volumes:
      - .:/recordings
    restart: unless-stopped
    environment:
      # Feel free to update this to your local timezone.
      # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
      - TZ=Asia/Tokyo
